import type { Metadata } from 'next';
import { IBM_Plex_Mono, Inter, Lato } from 'next/font/google';
import './globals.css';
import { AuthProvider } from './AuthProvider';

const ibmPlexMono = IBM_Plex_Mono({
    variable : '--font-ibm-plex-mono',
    subsets  : ['latin'],
    weight   : ['100', '200', '300', '400', '500', '600', '700']
});

const inter = Inter({
    variable : '--font-inter',
    subsets  : ['latin'],
    weight   : ['100', '200', '300', '400', '500', '600', '700']
});

const lato = Lato({
    variable : '--font-lato',
    subsets  : ['latin'],
    weight   : ['100',  '300', '400', '700']
});

export const metadata: Metadata = {
    title       : 'Create Next App',
    description : 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${lato.className} antialiased`}>
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
